runtime: nodejs10
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.6
  max_concurrent_requests: 20
resources:
  cpu: 1
  memory_gb: 0.7
  disk_size_gb: 10
