image: node:10

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            # Downloading the Google Cloud SDK
            - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
            - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
            - /tmp/google-cloud-sdk/install.sh -q
            - source /tmp/google-cloud-sdk/path.bash.inc
            - echo base64 --decode --ignore-garbage > ./node-js-firs-app-2ce55d294b58.json
            - gcloud auth activate-service-account test-account@node-js-firs-app.iam.gserviceaccount.com --key-file=node-js-firs-app-2ce55d294b58.json
            # Linking to the Google Cloud project
            - gcloud config set project node-js-firs-app
            - gcloud -q app deploy app.yaml